/* autogenerated by Processing revision 1286 on 2025-10-21 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Calculatorg extends PApplet {

//Gabriel Gonzales | 25 Sept 2025 | Calculator
Button[] buttons = new Button[13];
Button[] numButtons = new Button[10];
int i = 0;
Float l, r, result;
boolean left;
String dVal;
char op;

 public void setup() {
  /* size commented out by preprocessor */;
  background(0xFF0F0F0F);
  left = true;
  l = 0.0f;
  r = 0.0f;
  result = 0.0f;
  dVal = "0.0";
  op = ' ';
  buttons[0] = new Button(25, 70, 40, 30, 'C', 0xFFC96B1E, 0xFFDBD4D4);
  buttons[1] = new Button(75, 70, 40, 30, '±', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[2] = new Button(125, 70, 40, 30, '×', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[3] = new Button(175, 70, 40, 30, '÷', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[4] = new Button(225, 70, 40, 30, '^', 0xFF2C8CD8, 0xFFDBD4D4);
  numButtons[7] = new Button(25, 110, 40, 30, '7', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[8] = new Button(75, 110, 40, 30, '8', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[9] = new Button(125, 110, 40, 30, '9', 0xFFE5C831, 0xFFDBD4D4);
  buttons[5] = new Button(175, 110, 40, 30, '-', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[6] = new Button(225, 110, 40, 30, '√', 0xFF2C8CD8, 0xFFDBD4D4);
  numButtons[4] = new Button(25, 150, 40, 30, '4', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[5] = new Button(75, 150, 40, 30, '5', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[6] = new Button(125, 150, 40, 30, '6', 0xFFE5C831, 0xFFDBD4D4);
  buttons[7] = new Button(175, 150, 40, 30, '+', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[8] = new Button(225, 150, 40, 30, '|', 0xFF2C8CD8, 0xFFDBD4D4);
  numButtons[1] = new Button(25, 190, 40, 30, '1', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[2] = new Button(75, 190, 40, 30, '2', 0xFFE5C831, 0xFFDBD4D4);
  numButtons[3] = new Button(125, 190, 40, 30, '3', 0xFFE5C831, 0xFFDBD4D4);
  buttons[9] = new Button(175, 210, 40, 70, '=', 0xFF11BF9A, 0xFFDBD4D4);
  buttons[10] = new Button(225, 190, 40, 30, 'π', 0xFF2C8CD8, 0xFFDBD4D4);
  numButtons[0] = new Button(50, 230, 90, 30, '0', 0xFFE5C831, 0xFFDBD4D4);
  buttons[11] = new Button(125, 230, 40, 30, '.', 0xFFE5C831, 0xFFDBD4D4);
  buttons[12] = new Button(225, 230, 40, 30, 'p', 0xFF2C8CD8, 0xFFDBD4D4);
}

 public void draw() {
  background(0xFF0F0F0F);
  for (int i=0; i<buttons.length; i++) {
    buttons[i].display();
    buttons[i].hover(mouseX, mouseY);
  }
  for (int i=0; i<numButtons.length; i++) {
    numButtons[i].display();
    numButtons[i].hover(mouseX, mouseY);
  }
  updateDisplay();
}

 public void mousePressed() {
  // Not number buttons
  for (int i = 0; i<buttons.length; i++) {
    if (buttons[i].over && buttons[i].val == '+') {
      left = false;
      op = '+';
      dVal = "0.0";
    } else if (buttons[i].over && buttons[i].val == '-') {
      left = false;
      op = '-';
      dVal = "0.0";
    } else if (buttons[i].over && buttons[i].val == '÷') {
      left = false;
      op = '÷';
      dVal = "0.0";
    } else if (buttons[i].over && buttons[i].val == '×') {
      left = false;
      op = '×';
      dVal = "0.0";
    } else if (buttons[i].over && buttons[i].val == '±') {
      if (left) {
        l = l*-1;
        dVal = str(l);
      } else {
        r = r*-1;
        dVal = str(r);
      }
    } else if (buttons[i].over && buttons[i].val == '^') {
      if (left) {
        l = sq(l);
        dVal = str(l);
      } else {
        r = sq(r);
        dVal = str(r);
      }
    } else if (buttons[i].over && buttons[i].val == '√') {
      if (left) {
        l = sqrt(l);
        dVal = str(l);
      } else {
        r = sqrt(r);
        dVal = str(r);
      }
    } else if (buttons[i].over && buttons[i].val == '|') {
      if (left) {
        l = abs(l);
        dVal = str(l);
      } else {
        r = abs(r);
        dVal = str(r);
      }
    } else if (buttons[i].over && buttons[i].val == 'π') {
      if (left) {
        l = PI;
        dVal = str(l);
      } else {
        r = PI;
        dVal = str(r);
      }
    } else if (buttons[i].over && buttons[i].val == 'p') {
      dVal = "0.0";
      left = false;
      op = 'p';
    } else if (buttons[i].over && buttons[i].val == '=') {
      performCalculation();
    } else if (buttons[i].over && buttons[i].val == '.') {
      if (dVal.contains(".") == false) {
        dVal += ".";
      }
    } else if (buttons[i].over && buttons[i].val == 'C') {
      // all actions to clear calc
      left = true;
      l = 0.0f;
      r = 0.0f;
      result = 0.0f;
      dVal = "0.0";
      op = ' ';
    }
  }


  //All number buttons
  //dVal = "Pressed";
  for (int i = 0; i<numButtons.length; i++) {
    if (dVal.length()<18) {
      if (numButtons[i].over && left) {
        if (dVal.equals("0.0")) {
          dVal = str (numButtons[i].val);
          l = PApplet.parseFloat(dVal);
        } else {
          dVal += str (numButtons[i].val);
          l = PApplet.parseFloat(dVal);
        }
      } else if (numButtons[i].over && !left) {
        if (dVal.equals("0.0")) {
          dVal = str (numButtons[i].val);
          r = PApplet.parseFloat(dVal);
        } else {
          dVal += str (numButtons[i].val);
          r = PApplet.parseFloat(dVal);
        }
      }
    }
  }
  println("L:" + l);
  println("R:" + r);
  println("Result:" + result);
  println("Operator:" + op);
  println("Left:" + left);
}


 public void updateDisplay() {
  rectMode(CORNER);
  rect(5, 5, 240, 40, 25);
  fill(0);
  textSize(24);
  textAlign(RIGHT);
  if (dVal.length()<18) {
    textSize(25);
  } else if (dVal.length()>19) {
    textSize(25-2);
  }
  text(dVal, width-15, 35, 23);
}

 public void performCalculation() {
  if (op == '+') {
    result = (l + r);
  } else if (op == '-') {
    result = (l - r);
  } else if (op == '÷') {
    result = (l / r);
  } else if (op == '×') {
    result = (l * r);
  } else if (op == 'p') {
    result = pow(l, r);
  }
  dVal = str(result);
}
class Button {
  // Member Variables
  int x, y, w, h;
  char val;
  boolean over;
  int c1, c2;

  // Constructor
  Button(int x, int y, int w, int h, char val, int c1, int c2) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.val = val;
    over = false;
    this.c1 = c1;
    this.c2 = c2;
  }

  // Member methods
   public void display() {
    // Rectanlge Properties
    rectMode(CENTER);
    if(over == true) {
      fill(c2);
    } else {
    fill(c1);
    }
    strokeWeight(2);
    stroke(100);
    rect(x, y, w, h, 100);

    // Text Properties
    fill(255);
    textAlign(CENTER,CENTER);
    textSize(20);
    text(val, x, y);
  }

   public void hover(int tempX, int tempY) {
    if (x>tempX-w/2 && x<tempX+w/2 && y>tempY-h/2 && y<tempY+h/2) {
      over = true;
    } else {
      over = false;
    }
  }
}


  public void settings() { size(250, 250); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Calculatorg" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
